### PR TITLE
Game logic Implementation

### PR DESCRIPTION
**Pull request by acushlakoncept**
In this milestone of the project, we transformed the pseudo-codes of our last milestone into real game logic.
The game is separated into three classes, the Game, Player, and Board class and each has its own methods to modularize every action.

Here we enjoyed implementing the OOP concepts of Ruby.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @acushlakoncept and @ElijahTobs :clap: :clap:
#### Good job so far. However, you need to consider the following project required implementation before this project can be approved :point_down:

**_1. All game-logic related resources (classes and/or modules) should be kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). When you create separate files for each classes, remember that no `puts/print` and `get.chomp` is allowed outside `main.rb` file._**

**_2. Try to use `attr_readers/attr_writers`, only use `attr_accessors` if you really need to._**

**_Fix these required changes and submit for review._**

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Review by mikenath223 — CHANGES_REQUESTED** [review]
<h1>Hi Team 👋</h1>

Nice job on this.

However, let's fix this:

- [ ] REQUIRED - Kindly remove all puts and print statements in files in the lib directory. Puts and print statements should only be found in the `bin/main.rb` file.


Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

<h2>HAPPY CODING👨‍💻</h2>

**Review by davidmrtz-dev — APPROVED** [review]
****
## Hi Team. 😄 
****
Great Job 💯 👍  @acushlakoncept  @ElijahTobs , You correctly implemented the required changes.
You can move onto the next project. 🎊 
Happy coding. 👨‍🚀  
****
### Status: Approved. ✅
****

**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Pull request merged**
